org: sampleorg1
service: sample-jovi-app

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: Allow
      Action: "*"
      Resource: "*"
  environment:
    DYNAMODB_TABLE: sample-db-21
    BUCKET_NAME: sample-jovi-bucket

functions:
  insert:
    handler: insert.handler
    events:
      - httpApi:
          path: /insert
          method: post
  getSpecific:
    handler: getSpecific.getSpecific
    events:
      - httpApi:
          path: /get/{id}
          method: get
  getAll:
    handler: getAll.getAllRecords
    events:
      - httpApi:
          path: /
          method: get
          cors: true
  update:
    handler: update.update
    events:
      - httpApi:
          path: /update/{id}
          method: put
  delete:
    handler: delete.delete
    events:
      - httpApi:
          path: /delete/{id}
          method: delete
          cors: true
  upload:
    handler: getSignedUrl.signUrl
    events:
      - httpApi:
          path: /generate-signed-url
          method: get
