org: sampleorg1
service: my-serverless-app

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action: "*"
      Resource: "*"
  environment:
    DYNAMODB_TABLE: serverless-joshua-db
    # BUCKET_NAME: sample-jovi-bucket
  # httpApi:
  #   cors: true
  # ADD a KEYS for APIs
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:5173
        - http://192.168.1.6:5173
        - https://react-crud-serverless-jsh.netlify.app
      allowedHeaders:
      - Content-Type
      - Authorization
      - x-api-key
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowCredentials: true

functions:
  insert:
    handler: insert.handler
    events:
      - httpApi:
          path: /insert
          method: post
  getSpecific:
    handler: getSpecific.getSpecific
    events:
      - httpApi:
          path: /get/{id}
          method: get
  getAll:
    handler: getAll.getAllRecords
    events:
      - httpApi:
          path: /
          method: get
  update:
    handler: update.update
    events:
      - httpApi:
          path: /update/{id}
          method: put
  delete:
    handler: delete.delete
    events:
      - httpApi:
          path: /delete/{id}
          method: delete
  # upload:
  #   handler: getSignedUrl.signUrl
  #   events:
  #     - httpApi:
  #         path: /generate-signed-url
  #         method: get
